server:
  port: 8080
spring:
  application:
    #The name is not compulsory
    name: MenuEats
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/MenuEats?serverTimezone=Australia/Brisbane&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Yyq.500198
  mail:
    host: smtp.office365.com
    port: 587
    username: n10699155@qut.edu.au
    password: Yyq.s12023s1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
MenuEats:
  path: /Users/gary/Desktop/MenuEats/src/main/resources/backend/images/database-images/